import type { uvBoundsType } from '@types';

const FULL_UV_BOUNDS: uvBoundsType = { minX: 0, maxX: 1, minY: 0, maxY: 1 };
const DEFAULT_PART_TEXTURE_SIZE = 2048;
const PRINT_ATLAS_WIDTH = 2048;
const PRINT_ATLAS_HEIGHT = Math.round((4900 / 9331) * PRINT_ATLAS_WIDTH);
const PATTERN_LAYER_COUNT = 2;
const NAME_SLOT_COUNT = 4;
const LOGO_SLOT_COUNT = 4;

/** Corrects text/number orientation relative to the print UV space on the garment. */
const PRINT_UPLOAD_ROTATION_DEG = 90;

const NAME_REFERENCE_FONT_SIZE = 400;
const NAME_STAMP_STROKE_WIDTH_MAX = 20;
const NAME_STAMP_FONT_SIZE_MIN = 50;

const NAME_GIZMO_BTN_FILL_COLOR = '#ffffff';
const NAME_GIZMO_BTN_ACTIVE_COLOR = '#dc2c6f';
const NAME_GIZMO_ICON_COLOR = '#1a1a1a';
const NAME_GIZMO_UI_ATLAS_SCALE = 80 / NAME_REFERENCE_FONT_SIZE;
const NAME_GIZMO_BTN_HALF_ATLAS = 120 * NAME_GIZMO_UI_ATLAS_SCALE;
const NAME_GIZMO_BTN_OUTSET_ATLAS = 80 * NAME_GIZMO_UI_ATLAS_SCALE;

const LOGO_UPLOAD_ROTATION_DEG = PRINT_UPLOAD_ROTATION_DEG;
const LOGO_SCALE_MIN = 0.25;
const LOGO_SCALE_MAX = 3;
const LOGO_MARK_REF_WIDTH = 283 * 3;
const LOGO_ATLAS_REF_WIDTH = 9331;
const LOGO_ATLAS_REF_HEIGHT = 4900;

const FONT_FAMILY_BY_NAME: Record<string, string> = {
  Oswald: 'Oswald, sans-serif',
  'Bebas Neue': '"Bebas Neue", sans-serif',
  Anton: 'Anton, sans-serif',
  'Russo One': '"Russo One", sans-serif',
  'Black Ops One': '"Black Ops One", sans-serif',
};

export {
  DEFAULT_PART_TEXTURE_SIZE,
  FONT_FAMILY_BY_NAME,
  FULL_UV_BOUNDS,
  LOGO_ATLAS_REF_HEIGHT,
  LOGO_ATLAS_REF_WIDTH,
  LOGO_MARK_REF_WIDTH,
  LOGO_SCALE_MAX,
  LOGO_SCALE_MIN,
  LOGO_SLOT_COUNT,
  LOGO_UPLOAD_ROTATION_DEG,
  NAME_GIZMO_BTN_ACTIVE_COLOR,
  NAME_GIZMO_BTN_FILL_COLOR,
  NAME_GIZMO_BTN_HALF_ATLAS,
  NAME_GIZMO_BTN_OUTSET_ATLAS,
  NAME_GIZMO_ICON_COLOR,
  NAME_REFERENCE_FONT_SIZE,
  NAME_SLOT_COUNT,
  NAME_STAMP_FONT_SIZE_MIN,
  NAME_STAMP_STROKE_WIDTH_MAX,
  PATTERN_LAYER_COUNT,
  PRINT_ATLAS_HEIGHT,
  PRINT_ATLAS_WIDTH,
  PRINT_UPLOAD_ROTATION_DEG,
};
