const PRODUCT_SESSION_ROW_HOVER_TRANSITION_MS = 200;
const PRODUCT_SESSION_ROW_SCROLL_EDGE_PADDING_PX = 8;

export { PRODUCT_SESSION_ROW_HOVER_TRANSITION_MS, PRODUCT_SESSION_ROW_SCROLL_EDGE_PADDING_PX };
