const PRODUCT_SESSION_ROW_HOVER_TRANSITION_MS = 200;
const PRODUCT_SESSION_ROW_CARD_WIDTH_PX = 48;
const PRODUCT_SESSION_ROW_CARD_HEIGHT_PX = 44;
const PRODUCT_SESSION_ROW_EXPANDED_WIDTH_PX = 131;
const PRODUCT_SESSION_ROW_PREVIEW_SIZE_PX = 28;
const PRODUCT_SESSION_ROW_SCROLL_EDGE_PADDING_PX = 8;
const PRODUCT_SESSION_ROW_EXPANDED_VIEWPORT_PADDING_PX = 16;

export {
  PRODUCT_SESSION_ROW_CARD_HEIGHT_PX,
  PRODUCT_SESSION_ROW_CARD_WIDTH_PX,
  PRODUCT_SESSION_ROW_EXPANDED_VIEWPORT_PADDING_PX,
  PRODUCT_SESSION_ROW_EXPANDED_WIDTH_PX,
  PRODUCT_SESSION_ROW_HOVER_TRANSITION_MS,
  PRODUCT_SESSION_ROW_PREVIEW_SIZE_PX,
  PRODUCT_SESSION_ROW_SCROLL_EDGE_PADDING_PX,
};
