type textVariantType =
  | 'default'
  | 'whatsapp_badge'
  | 'product_name'
  | 'product_name_no_margin'
  | 'product_price'
  | 'product_price_mobile_only'
  | 'menu_step_buy'
  | 'slider_label'
  | 'configurator_part_label'
  | 'configurator_control_label'
  | 'configurator_control_label_shrink'
  | 'configurator_brand_logo_description'
  | 'configurator_brand_logo_title'
  | 'configurator_brand_logo_title_clamped'
  | 'configurator_product_description'
  | 'configurator_product_badge_title'
  | 'configurator_product_minimum'
  | 'configurator_product_volume_discount'
  | 'loader_tagline'
  | 'logo_uploaded_label'
  | 'logo_uploaded_label_dark'
  | 'logo_uploaded_hint'
  | 'logo_uploaded_file_name'
  | 'logo_upload_cta_primary'
  | 'logo_upload_cta_secondary'
  | 'error_xs'
  | 'checkout_empty_cart_title'
  | 'checkout_mobile_note'
  | 'checkout_quantity_value'
  | 'checkout_modal_field_label'
  | 'checkout_small_secondary_mobile'
  | 'checkout_small_secondary_mobile_default'
  | 'checkout_summary_discount_title'
  | 'checkout_summary_discount_subtitle'
  | 'checkout_summary_item_name_default'
  | 'checkout_summary_item_name_compact'
  | 'checkout_summary_price_default'
  | 'checkout_summary_price_compact'
  | 'checkout_summary_shipping_label_default'
  | 'checkout_summary_shipping_label_compact'
  | 'checkout_summary_total_label_default'
  | 'checkout_summary_total_label_compact'
  | 'checkout_summary_vat_note'
  | 'checkout_summary_timeline_title'
  | 'checkout_summary_timeline_step_label'
  | 'checkout_summary_timeline_step_date'
  | 'checkout_summary_trust_label'
  | 'checkout_summary_mobile_total_label'
  | 'checkout_summary_mobile_vat_label'
  | 'checkout_summary_mobile_total_amount'
  | 'checkout_summary_drawer_title'
  | 'aside_help_title'
  | 'catalog_popover_title'
  | 'product_session_name'
  | 'rich_text'
  | 'h2'
  | 'h3'
  | 'h3_italic_uppercase'
  | 'small'
  | 'small_secondary'
  | 'product_card_name';

type boxVariantType =
  | 'default'
  | 'header'
  | 'footer'
  | 'toggle_handle'
  | 'aside_configuration'
  | 'aside_utility'
  | 'responsive_hidden_mobile'
  | 'responsive_mobile_only'
  | 'content_panel'
  | 'info_image_wrapper'
  | 'palette_carousel_mobile'
  | 'hidden_mobile'
  | 'relative_fill'
  | 'skeleton_card_surface'
  | 'checkout_quantity_badge'
  | 'notification_dot'
  | 'shrink_0'
  | 'video_preview_root'
  | 'brand_logo_placeholder_shell'
  | 'catalog_option_media_frame'
  | 'flex_1'
  | 'loader_content_layer'
  | 'checkout_table_root'
  | 'checkout_table_shell'
  | 'modal_info_table_shell'
  | 'canvas_loader_background'
  | 'modal_tabs_padding'
  | 'order_cutting_preview_shell'
  | 'order_cutting_preview_card'
  | 'desktop_only_block'
  | 'mobile_only_block'
  | 'configurator_shell'
  | 'configurator_shell_background'
  | 'configurator_shell_grid'
  | 'configurator_view_placeholder'
  | 'tabs_list_wrapper'
  | 'checkout_product_details_panel'
  | 'checkout_product_details_open'
  | 'checkout_product_details_closed'
  | 'checkout_row_field_shell'
  | 'checkout_row_field_shell_center'
  | 'cutting_export_download_preview_frame'
  | 'product_flip_card_inner'
  | 'product_flip_card_front'
  | 'product_flip_card_back'
  | 'video_player_frame'
  | 'video_player_overlay'
  | 'main_loader_background_root'
  | 'main_loader_background_glow'
  | 'main_loader_background_top_fade'
  | 'main_loader_host';

type flexVariantType =
  | 'default'
  | 'utility_bar'
  | 'search_bar'
  | 'user_bar'
  | 'step_design'
  | 'aside_configurator_content'
  | 'configurator_part'
  | 'configurator_part_clipped'
  | 'slider_labels'
  | 'info_part'
  | 'header_configuration'
  | 'configurator_layout_template'
  | 'configurator_view'
  | 'configurator_view_canvas'
  | 'product_card_name'
  | 'card_add_product'
  | 'aside_utility_column'
  | 'aside_utility_help_panel'
  | 'between_aligned_full'
  | 'control_primary_column'
  | 'logo_upload_section'
  | 'logo_edit_panel_column'
  | 'logo_uploaded_section'
  | 'logo_uploaded_list'
  | 'brand_placeholder_column'
  | 'brand_placeholder_row'
  | 'skeleton_column_full_gap3'
  | 'skeleton_column_full_gap2'
  | 'skeleton_row_center_gap2'
  | 'skeleton_card_column'
  | 'skeleton_inner_column'
  | 'skeleton_hint_row'
  | 'loader_column_center_gap5'
  | 'logo_pair_row'
  | 'overlay_center_column'
  | 'checkout_empty_state'
  | 'checkout_content_column'
  | 'checkout_mobile_note_column'
  | 'footer_desktop_row'
  | 'footer_mobile_column'
  | 'footer_mobile_grid'
  | 'checkout_modal_content_column'
  | 'checkout_modal_field_group'
  | 'checkout_modal_actions_column'
  | 'checkout_product_layout'
  | 'checkout_product_details'
  | 'checkout_product_quantity_row'
  | 'checkout_product_quantity_inner'
  | 'checkout_product_side_column'
  | 'checkout_product_meta_row'
  | 'skeleton_step_inner_column'
  | 'skeleton_row_center_gap3'
  | 'checkout_summary_between_row'
  | 'checkout_summary_between_wrap_row'
  | 'checkout_summary_item_inline'
  | 'checkout_summary_total_label_column'
  | 'checkout_summary_section_column'
  | 'checkout_summary_timeline_column'
  | 'checkout_summary_timeline_row'
  | 'checkout_summary_timeline_step_column'
  | 'checkout_summary_timeline_icon'
  | 'checkout_summary_body_column'
  | 'checkout_summary_actions_column'
  | 'checkout_mobile_note_left_column'
  | 'full_width'
  | 'centered_inline'
  | 'card_list_column'
  | 'skeleton_logo_upload_column'
  | 'skeleton_configurator_root'
  | 'skeleton_configurator_meta'
  | 'step_design_mobile_padded'
  | 'modal_add_product_preview_row'
  | 'modal_add_product_actions'
  | 'share_dialog_row'
  | 'part_color_switch_row'
  | 'part_color_switch_inner'
  | 'configurator_product_root'
  | 'configurator_product_badge'
  | 'modal_info_tab_content'
  | 'modal_info_parts_column'
  | 'modal_info_text_part'
  | 'modal_info_text_part_left'
  | 'logo_list_actions'
  | 'step_design_compact'
  | 'configurator_part_spaced'
  | 'step_design_logo_column'
  | 'checkout_cell_row'
  | 'checkout_cell_row_start'
  | 'checkout_cell_row_center'
  | 'checkout_cell_actions_row'
  | 'checkout_cell_actions_between'
  | 'checkout_cell_actions_center'
  | 'checkout_placeholder_row'
  | 'product_session_preview_frame'
  | 'product_session_preview_center'
  | 'range_control_clipped'
  | 'color_control_panel'
  | 'checkout_summary_list_compact'
  | 'checkout_summary_list_default'
  | 'checkout_summary_meta_compact'
  | 'checkout_summary_meta_default'
  | 'checkout_product_actions'
  | 'tab_control_header'
  | 'checkout_summary_mobile_actions'
  | 'checkout_summary_mobile_head'
  | 'checkout_summary_mobile_total'
  | 'checkout_summary_mobile_total_labels'
  | 'checkout_summary_mobile_content'
  | 'checkout_summary_drawer_container'
  | 'checkout_summary_drawer_header'
  | 'checkout_summary_drawer_sections'
  | 'checkout_summary_drawer_separator'
  | 'checkout_summary_drawer_footer'
  | 'checkout_summary_drawer_handle'
  | 'last_order_page_column'
  | 'last_order_meta_column';

type gridVariantType =
  | 'default'
  | 'header'
  | 'configurator'
  | 'configurator_price'
  | 'select_parts'
  | 'aside_configurator'
  | 'aside_utility_actions'
  | 'aside_configuration_layout'
  | 'logo_info_panel'
  | 'logo_list_row'
  | 'logo_list_identity'
  | 'logo_edit_header'
  | 'color_control_actions'
  | 'select_parts_mobile_hidden'
  | 'checkout_view_layout'
  | 'footer_notification'
  | 'configurator_product_header'
  | 'gallery_four_cols'
  | 'catalog_dialog_grid'
  | 'select_parts_minw0'
  | 'skeleton_logo_info_panel'
  | 'skeleton_configurator_header'
  | 'configurator_price_spaced'
  | 'position_picker_grid';

type atomImageVariantType = 'default' | 'logo' | 'logo_full';

type atomTabsVariantType = 'default' | 'line' | 'configurator' | 'modal';

type atomTabsSlidingListPresetType = 'configurator' | 'modal';

type atomTableVariantType = 'default' | 'size_chart' | 'discounts' | 'checkout';

type atomListVariantType = 'default' | 'faq';

type slidingIndicatorVariantType = 'gradient' | 'solid';

type slidingIndicatorTrackVariantType = 'default' | 'none';

export type {
  atomImageVariantType,
  atomListVariantType,
  atomTableVariantType,
  atomTabsSlidingListPresetType,
  atomTabsVariantType,
  boxVariantType,
  flexVariantType,
  gridVariantType,
  slidingIndicatorTrackVariantType,
  slidingIndicatorVariantType,
  textVariantType,
};
