const CONFIGURATOR_PRODUCT_DESCRIPTION = "Eventuali liste dei giocatori, quantità e taglie da inserire dopo in 'Completa config.'";

const CONFIGURATOR_GRADIENT_ACTIVE_LABEL = 'Sfumatura attiva';

const CONFIGURATOR_NAME_POSITION_SELECT_LABEL = 'Dove desideri inserire il nome?';
const CONFIGURATOR_NUMBER_POSITION_SELECT_LABEL = 'Dove desideri inserire il numero?';
const CONFIGURATOR_TESTO_POSITION_SELECT_LABEL = 'Dove desideri inserire il testo?';
const CONFIGURATOR_POSITION_SELECT_PLACEHOLDER = 'Seleziona posizione';

const CONFIGURATOR_UPLOADED_FILES_LABEL = 'File caricati';

const CONFIGURATOR_DEFAULT_BRAND_LOGO_TITLE = 'Brand Logo';

const CONFIGURATOR_DEFAULT_BRAND_LOGO_DESCRIPTION = 'I loghi di Realize cambieranno colore per adattarsi alla grafica senza preavviso.';

const CONFIGURATOR_DEFAULT_BRAND_LOGO_SRC = '/svg/logo.svg';

export {
  CONFIGURATOR_DEFAULT_BRAND_LOGO_DESCRIPTION,
  CONFIGURATOR_DEFAULT_BRAND_LOGO_SRC,
  CONFIGURATOR_DEFAULT_BRAND_LOGO_TITLE,
  CONFIGURATOR_GRADIENT_ACTIVE_LABEL,
  CONFIGURATOR_NAME_POSITION_SELECT_LABEL,
  CONFIGURATOR_NUMBER_POSITION_SELECT_LABEL,
  CONFIGURATOR_TESTO_POSITION_SELECT_LABEL,
  CONFIGURATOR_POSITION_SELECT_PLACEHOLDER,
  CONFIGURATOR_PRODUCT_DESCRIPTION,
  CONFIGURATOR_UPLOADED_FILES_LABEL,
};
