export {
  CONFIGURATOR_DEFAULT_BRAND_LOGO_DESCRIPTION,
  CONFIGURATOR_DEFAULT_BRAND_LOGO_SRC,
  CONFIGURATOR_DEFAULT_BRAND_LOGO_TITLE,
  CONFIGURATOR_GRADIENT_ACTIVE_LABEL,
  CONFIGURATOR_NAME_POSITION_SELECT_LABEL,
  CONFIGURATOR_NUMBER_POSITION_SELECT_LABEL,
  CONFIGURATOR_TESTO_POSITION_SELECT_LABEL,
  CONFIGURATOR_POSITION_SELECT_PLACEHOLDER,
  CONFIGURATOR_PRODUCT_DESCRIPTION,
  CONFIGURATOR_UPLOADED_FILES_LABEL,
} from './CONFIGURATOR';
