const STEP_COLOR = 1;
const STEP_DESIGN = 2;
const STEP_SHADING = 3;
const STEP_NAME = 4;
const STEP_NUMBER = 5;
const STEP_TESTO = 6;
const STEP_LOGO = 7;

export { STEP_COLOR, STEP_DESIGN, STEP_LOGO, STEP_NAME, STEP_NUMBER, STEP_SHADING, STEP_TESTO };
